# Generated by Django 3.1.12 on 2021-12-07 11:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_title', models.CharField(max_length=100)),
                ('brief_component', models.TextField()),
                ('price_before', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_after', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lifeStage', models.CharField(choices=[('puppy', 'puppy'), ('adult', 'adult'), ('senior', 'senior')], max_length=50)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail_front_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('description', models.TextField()),
                ('nutrition_info', models.TextField()),
                ('deliver_info', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
