# Generated by Django 3.1.12 on 2021-12-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
